// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: product/product_command.proto

package pb_product

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    int32                  `protobuf:"varint,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	CategoryId    int32                  `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Price         int32                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	CountInStock  int32                  `protobuf:"varint,6,opt,name=count_in_stock,json=countInStock,proto3" json:"count_in_stock,omitempty"`
	Brand         string                 `protobuf:"bytes,7,opt,name=brand,proto3" json:"brand,omitempty"`
	Weight        int32                  `protobuf:"varint,8,opt,name=weight,proto3" json:"weight,omitempty"`
	Rating        int32                  `protobuf:"varint,9,opt,name=rating,proto3" json:"rating,omitempty"`
	SlugProduct   string                 `protobuf:"bytes,10,opt,name=slug_product,json=slugProduct,proto3" json:"slug_product,omitempty"`
	ImageProduct  string                 `protobuf:"bytes,11,opt,name=image_product,json=imageProduct,proto3" json:"image_product,omitempty"`
	Barcode       string                 `protobuf:"bytes,12,opt,name=barcode,proto3" json:"barcode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_product_product_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_product_product_command_proto_rawDescGZIP(), []int{0}
}

func (x *CreateProductRequest) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *CreateProductRequest) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CreateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProductRequest) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateProductRequest) GetCountInStock() int32 {
	if x != nil {
		return x.CountInStock
	}
	return 0
}

func (x *CreateProductRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *CreateProductRequest) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *CreateProductRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *CreateProductRequest) GetSlugProduct() string {
	if x != nil {
		return x.SlugProduct
	}
	return ""
}

func (x *CreateProductRequest) GetImageProduct() string {
	if x != nil {
		return x.ImageProduct
	}
	return ""
}

func (x *CreateProductRequest) GetBarcode() string {
	if x != nil {
		return x.Barcode
	}
	return ""
}

type UpdateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int32                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	MerchantId    int32                  `protobuf:"varint,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	CategoryId    int32                  `protobuf:"varint,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Price         int32                  `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
	CountInStock  int32                  `protobuf:"varint,7,opt,name=count_in_stock,json=countInStock,proto3" json:"count_in_stock,omitempty"`
	Brand         string                 `protobuf:"bytes,8,opt,name=brand,proto3" json:"brand,omitempty"`
	Weight        int32                  `protobuf:"varint,9,opt,name=weight,proto3" json:"weight,omitempty"`
	Rating        int32                  `protobuf:"varint,10,opt,name=rating,proto3" json:"rating,omitempty"`
	SlugProduct   string                 `protobuf:"bytes,11,opt,name=slug_product,json=slugProduct,proto3" json:"slug_product,omitempty"`
	ImageProduct  string                 `protobuf:"bytes,12,opt,name=image_product,json=imageProduct,proto3" json:"image_product,omitempty"`
	Barcode       string                 `protobuf:"bytes,13,opt,name=barcode,proto3" json:"barcode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductRequest) Reset() {
	*x = UpdateProductRequest{}
	mi := &file_product_product_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRequest) ProtoMessage() {}

func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_product_product_command_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateProductRequest) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *UpdateProductRequest) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *UpdateProductRequest) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *UpdateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateProductRequest) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateProductRequest) GetCountInStock() int32 {
	if x != nil {
		return x.CountInStock
	}
	return 0
}

func (x *UpdateProductRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *UpdateProductRequest) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *UpdateProductRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *UpdateProductRequest) GetSlugProduct() string {
	if x != nil {
		return x.SlugProduct
	}
	return ""
}

func (x *UpdateProductRequest) GetImageProduct() string {
	if x != nil {
		return x.ImageProduct
	}
	return ""
}

func (x *UpdateProductRequest) GetBarcode() string {
	if x != nil {
		return x.Barcode
	}
	return ""
}

type UpdateProductCountStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int32                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Stock         int32                  `protobuf:"varint,2,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductCountStockRequest) Reset() {
	*x = UpdateProductCountStockRequest{}
	mi := &file_product_product_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductCountStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductCountStockRequest) ProtoMessage() {}

func (x *UpdateProductCountStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductCountStockRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductCountStockRequest) Descriptor() ([]byte, []int) {
	return file_product_product_command_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateProductCountStockRequest) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *UpdateProductCountStockRequest) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type AdjustProductStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int32                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Delta         int32                  `protobuf:"varint,2,opt,name=delta,proto3" json:"delta,omitempty"`
	OperationId   string                 `protobuf:"bytes,3,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdjustProductStockRequest) Reset() {
	*x = AdjustProductStockRequest{}
	mi := &file_product_product_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdjustProductStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjustProductStockRequest) ProtoMessage() {}

func (x *AdjustProductStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjustProductStockRequest.ProtoReflect.Descriptor instead.
func (*AdjustProductStockRequest) Descriptor() ([]byte, []int) {
	return file_product_product_command_proto_rawDescGZIP(), []int{3}
}

func (x *AdjustProductStockRequest) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *AdjustProductStockRequest) GetDelta() int32 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *AdjustProductStockRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type CleanupProductStockAdjustmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetentionDays int32                  `protobuf:"varint,1,opt,name=retention_days,json=retentionDays,proto3" json:"retention_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanupProductStockAdjustmentsRequest) Reset() {
	*x = CleanupProductStockAdjustmentsRequest{}
	mi := &file_product_product_command_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupProductStockAdjustmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupProductStockAdjustmentsRequest) ProtoMessage() {}

func (x *CleanupProductStockAdjustmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_command_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupProductStockAdjustmentsRequest.ProtoReflect.Descriptor instead.
func (*CleanupProductStockAdjustmentsRequest) Descriptor() ([]byte, []int) {
	return file_product_product_command_proto_rawDescGZIP(), []int{4}
}

func (x *CleanupProductStockAdjustmentsRequest) GetRetentionDays() int32 {
	if x != nil {
		return x.RetentionDays
	}
	return 0
}

type CleanupProductStockAdjustmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Deleted       int64                  `protobuf:"varint,3,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanupProductStockAdjustmentsResponse) Reset() {
	*x = CleanupProductStockAdjustmentsResponse{}
	mi := &file_product_product_command_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupProductStockAdjustmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupProductStockAdjustmentsResponse) ProtoMessage() {}

func (x *CleanupProductStockAdjustmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_command_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupProductStockAdjustmentsResponse.ProtoReflect.Descriptor instead.
func (*CleanupProductStockAdjustmentsResponse) Descriptor() ([]byte, []int) {
	return file_product_product_command_proto_rawDescGZIP(), []int{5}
}

func (x *CleanupProductStockAdjustmentsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CleanupProductStockAdjustmentsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CleanupProductStockAdjustmentsResponse) GetDeleted() int64 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

var File_product_product_command_proto protoreflect.FileDescriptor

const file_product_product_command_proto_rawDesc = "" +
	"\n" +
	"\x1dproduct/product_command.proto\x12\n" +
	"pb.product\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cproduct/product_common.proto\"\xf2\x02\n" +
	"\x14CreateProductRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\x05R\n" +
	"merchantId\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\x05R\n" +
	"categoryId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x05R\x05price\x12$\n" +
	"\x0ecount_in_stock\x18\x06 \x01(\x05R\fcountInStock\x12\x14\n" +
	"\x05brand\x18\a \x01(\tR\x05brand\x12\x16\n" +
	"\x06weight\x18\b \x01(\x05R\x06weight\x12\x16\n" +
	"\x06rating\x18\t \x01(\x05R\x06rating\x12!\n" +
	"\fslug_product\x18\n" +
	" \x01(\tR\vslugProduct\x12#\n" +
	"\rimage_product\x18\v \x01(\tR\fimageProduct\x12\x18\n" +
	"\abarcode\x18\f \x01(\tR\abarcode\"\x91\x03\n" +
	"\x14UpdateProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x05R\tproductId\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\x05R\n" +
	"merchantId\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\x05R\n" +
	"categoryId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x05R\x05price\x12$\n" +
	"\x0ecount_in_stock\x18\a \x01(\x05R\fcountInStock\x12\x14\n" +
	"\x05brand\x18\b \x01(\tR\x05brand\x12\x16\n" +
	"\x06weight\x18\t \x01(\x05R\x06weight\x12\x16\n" +
	"\x06rating\x18\n" +
	" \x01(\x05R\x06rating\x12!\n" +
	"\fslug_product\x18\v \x01(\tR\vslugProduct\x12#\n" +
	"\rimage_product\x18\f \x01(\tR\fimageProduct\x12\x18\n" +
	"\abarcode\x18\r \x01(\tR\abarcode\"U\n" +
	"\x1eUpdateProductCountStockRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x05R\tproductId\x12\x14\n" +
	"\x05stock\x18\x02 \x01(\x05R\x05stock\"s\n" +
	"\x19AdjustProductStockRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x05R\tproductId\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\x05R\x05delta\x12!\n" +
	"\foperation_id\x18\x03 \x01(\tR\voperationId\"N\n" +
	"%CleanupProductStockAdjustmentsRequest\x12%\n" +
	"\x0eretention_days\x18\x01 \x01(\x05R\rretentionDays\"t\n" +
	"&CleanupProductStockAdjustmentsResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\adeleted\x18\x03 \x01(\x03R\adeleted2\xc5\a\n" +
	"\x15ProductCommandService\x12J\n" +
	"\x06Create\x12 .pb.product.CreateProductRequest\x1a\x1e.pb.product.ApiResponseProduct\x12J\n" +
	"\x06Update\x12 .pb.product.UpdateProductRequest\x1a\x1e.pb.product.ApiResponseProduct\x12e\n" +
	"\x17UpdateProductCountStock\x12*.pb.product.UpdateProductCountStockRequest\x1a\x1e.pb.product.ApiResponseProduct\x12[\n" +
	"\x12AdjustProductStock\x12%.pb.product.AdjustProductStockRequest\x1a\x1e.pb.product.ApiResponseProduct\x12\x87\x01\n" +
	"\x1eCleanupProductStockAdjustments\x121.pb.product.CleanupProductStockAdjustmentsRequest\x1a2.pb.product.CleanupProductStockAdjustmentsResponse\x12\\\n" +
	"\x0eTrashedProduct\x12\".pb.product.FindByIdProductRequest\x1a&.pb.product.ApiResponseProductDeleteAt\x12\\\n" +
	"\x0eRestoreProduct\x12\".pb.product.FindByIdProductRequest\x1a&.pb.product.ApiResponseProductDeleteAt\x12b\n" +
	"\x16DeleteProductPermanent\x12\".pb.product.FindByIdProductRequest\x1a$.pb.product.ApiResponseProductDelete\x12N\n" +
	"\x11RestoreAllProduct\x12\x16.google.protobuf.Empty\x1a!.pb.product.ApiResponseProductAll\x12V\n" +
	"\x19DeleteAllProductPermanent\x12\x16.google.protobuf.Empty\x1a!.pb.product.ApiResponseProductAllBIZGgithub.com/MamangRust/microservice-ecommerce-grpc-pb/product;pb_productb\x06proto3"

var (
	file_product_product_command_proto_rawDescOnce sync.Once
	file_product_product_command_proto_rawDescData []byte
)

func file_product_product_command_proto_rawDescGZIP() []byte {
	file_product_product_command_proto_rawDescOnce.Do(func() {
		file_product_product_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_product_command_proto_rawDesc), len(file_product_product_command_proto_rawDesc)))
	})
	return file_product_product_command_proto_rawDescData
}

var file_product_product_command_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_product_product_command_proto_goTypes = []any{
	(*CreateProductRequest)(nil),                   // 0: pb.product.CreateProductRequest
	(*UpdateProductRequest)(nil),                   // 1: pb.product.UpdateProductRequest
	(*UpdateProductCountStockRequest)(nil),         // 2: pb.product.UpdateProductCountStockRequest
	(*AdjustProductStockRequest)(nil),              // 3: pb.product.AdjustProductStockRequest
	(*CleanupProductStockAdjustmentsRequest)(nil),  // 4: pb.product.CleanupProductStockAdjustmentsRequest
	(*CleanupProductStockAdjustmentsResponse)(nil), // 5: pb.product.CleanupProductStockAdjustmentsResponse
	(*FindByIdProductRequest)(nil),                 // 6: pb.product.FindByIdProductRequest
	(*emptypb.Empty)(nil),                          // 7: google.protobuf.Empty
	(*ApiResponseProduct)(nil),                     // 8: pb.product.ApiResponseProduct
	(*ApiResponseProductDeleteAt)(nil),             // 9: pb.product.ApiResponseProductDeleteAt
	(*ApiResponseProductDelete)(nil),               // 10: pb.product.ApiResponseProductDelete
	(*ApiResponseProductAll)(nil),                  // 11: pb.product.ApiResponseProductAll
}
var file_product_product_command_proto_depIdxs = []int32{
	0,  // 0: pb.product.ProductCommandService.Create:input_type -> pb.product.CreateProductRequest
	1,  // 1: pb.product.ProductCommandService.Update:input_type -> pb.product.UpdateProductRequest
	2,  // 2: pb.product.ProductCommandService.UpdateProductCountStock:input_type -> pb.product.UpdateProductCountStockRequest
	3,  // 3: pb.product.ProductCommandService.AdjustProductStock:input_type -> pb.product.AdjustProductStockRequest
	4,  // 4: pb.product.ProductCommandService.CleanupProductStockAdjustments:input_type -> pb.product.CleanupProductStockAdjustmentsRequest
	6,  // 5: pb.product.ProductCommandService.TrashedProduct:input_type -> pb.product.FindByIdProductRequest
	6,  // 6: pb.product.ProductCommandService.RestoreProduct:input_type -> pb.product.FindByIdProductRequest
	6,  // 7: pb.product.ProductCommandService.DeleteProductPermanent:input_type -> pb.product.FindByIdProductRequest
	7,  // 8: pb.product.ProductCommandService.RestoreAllProduct:input_type -> google.protobuf.Empty
	7,  // 9: pb.product.ProductCommandService.DeleteAllProductPermanent:input_type -> google.protobuf.Empty
	8,  // 10: pb.product.ProductCommandService.Create:output_type -> pb.product.ApiResponseProduct
	8,  // 11: pb.product.ProductCommandService.Update:output_type -> pb.product.ApiResponseProduct
	8,  // 12: pb.product.ProductCommandService.UpdateProductCountStock:output_type -> pb.product.ApiResponseProduct
	8,  // 13: pb.product.ProductCommandService.AdjustProductStock:output_type -> pb.product.ApiResponseProduct
	5,  // 14: pb.product.ProductCommandService.CleanupProductStockAdjustments:output_type -> pb.product.CleanupProductStockAdjustmentsResponse
	9,  // 15: pb.product.ProductCommandService.TrashedProduct:output_type -> pb.product.ApiResponseProductDeleteAt
	9,  // 16: pb.product.ProductCommandService.RestoreProduct:output_type -> pb.product.ApiResponseProductDeleteAt
	10, // 17: pb.product.ProductCommandService.DeleteProductPermanent:output_type -> pb.product.ApiResponseProductDelete
	11, // 18: pb.product.ProductCommandService.RestoreAllProduct:output_type -> pb.product.ApiResponseProductAll
	11, // 19: pb.product.ProductCommandService.DeleteAllProductPermanent:output_type -> pb.product.ApiResponseProductAll
	10, // [10:20] is the sub-list for method output_type
	0,  // [0:10] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_product_product_command_proto_init() }
func file_product_product_command_proto_init() {
	if File_product_product_command_proto != nil {
		return
	}
	file_product_product_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_product_command_proto_rawDesc), len(file_product_product_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_product_command_proto_goTypes,
		DependencyIndexes: file_product_product_command_proto_depIdxs,
		MessageInfos:      file_product_product_command_proto_msgTypes,
	}.Build()
	File_product_product_command_proto = out.File
	file_product_product_command_proto_goTypes = nil
	file_product_product_command_proto_depIdxs = nil
}
